-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.DiscussionSettings exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| Allow people to submit comments on new posts.
-}
defaultCommentStatus : SelectionSet (Maybe String) Taco.Object.DiscussionSettings
defaultCommentStatus =
      Object.selectionForField "(Maybe String)" "defaultCommentStatus" [] (Decode.string |> Decode.nullable)


{-| Allow link notifications from other blogs (pingbacks and trackbacks) on new articles.
-}
defaultPingStatus : SelectionSet (Maybe String) Taco.Object.DiscussionSettings
defaultPingStatus =
      Object.selectionForField "(Maybe String)" "defaultPingStatus" [] (Decode.string |> Decode.nullable)
