-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.EnqueuedScript exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| @todo
-}
args : SelectionSet (Maybe Bool) Taco.Object.EnqueuedScript
args =
      Object.selectionForField "(Maybe Bool)" "args" [] (Decode.bool |> Decode.nullable)


{-| Dependencies needed to use this asset
-}
dependencies : SelectionSet decodesTo Taco.Object.EnqueuedScript
 -> SelectionSet (Maybe (List (Maybe decodesTo))) Taco.Object.EnqueuedScript
dependencies object____ =
      Object.selectionForCompositeField "dependencies" [] (object____) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Extra information needed for the script
-}
extra : SelectionSet (Maybe String) Taco.Object.EnqueuedScript
extra =
      Object.selectionForField "(Maybe String)" "extra" [] (Decode.string |> Decode.nullable)


{-| The handle of the enqueued asset
-}
handle : SelectionSet (Maybe String) Taco.Object.EnqueuedScript
handle =
      Object.selectionForField "(Maybe String)" "handle" [] (Decode.string |> Decode.nullable)


{-| The globally unique ID for the object
-}
id : SelectionSet Taco.ScalarCodecs.Id Taco.Object.EnqueuedScript
id =
      Object.selectionForField "ScalarCodecs.Id" "id" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The source of the asset
-}
src : SelectionSet (Maybe String) Taco.Object.EnqueuedScript
src =
      Object.selectionForField "(Maybe String)" "src" [] (Decode.string |> Decode.nullable)


{-| The version of the enqueued asset
-}
version : SelectionSet (Maybe String) Taco.Object.EnqueuedScript
version =
      Object.selectionForField "(Maybe String)" "version" [] (Decode.string |> Decode.nullable)
