-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.MediaSize exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| The file of the for the referenced size
-}
file : SelectionSet (Maybe String) Taco.Object.MediaSize
file =
      Object.selectionForField "(Maybe String)" "file" [] (Decode.string |> Decode.nullable)


{-| The filesize of the resource
-}
fileSize : SelectionSet (Maybe Int) Taco.Object.MediaSize
fileSize =
      Object.selectionForField "(Maybe Int)" "fileSize" [] (Decode.int |> Decode.nullable)


{-| The height of the for the referenced size
-}
height : SelectionSet (Maybe String) Taco.Object.MediaSize
height =
      Object.selectionForField "(Maybe String)" "height" [] (Decode.string |> Decode.nullable)


{-| The mime type of the resource
-}
mimeType : SelectionSet (Maybe String) Taco.Object.MediaSize
mimeType =
      Object.selectionForField "(Maybe String)" "mimeType" [] (Decode.string |> Decode.nullable)


{-| The referenced size name
-}
name : SelectionSet (Maybe String) Taco.Object.MediaSize
name =
      Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The url of the for the referenced size
-}
sourceUrl : SelectionSet (Maybe String) Taco.Object.MediaSize
sourceUrl =
      Object.selectionForField "(Maybe String)" "sourceUrl" [] (Decode.string |> Decode.nullable)


{-| The width of the for the referenced size
-}
width : SelectionSet (Maybe String) Taco.Object.MediaSize
width =
      Object.selectionForField "(Maybe String)" "width" [] (Decode.string |> Decode.nullable)
