-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.MediaDetails exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| The height of the mediaItem
-}
file : SelectionSet (Maybe String) Taco.Object.MediaDetails
file =
      Object.selectionForField "(Maybe String)" "file" [] (Decode.string |> Decode.nullable)


{-| The height of the mediaItem
-}
height : SelectionSet (Maybe Int) Taco.Object.MediaDetails
height =
      Object.selectionForField "(Maybe Int)" "height" [] (Decode.int |> Decode.nullable)


{-| 
-}
meta : SelectionSet decodesTo Taco.Object.MediaItemMeta
 -> SelectionSet (Maybe decodesTo) Taco.Object.MediaDetails
meta object____ =
      Object.selectionForCompositeField "meta" [] (object____) (identity >> Decode.nullable)


{-| The available sizes of the mediaItem
-}
sizes : SelectionSet decodesTo Taco.Object.MediaSize
 -> SelectionSet (Maybe (List (Maybe decodesTo))) Taco.Object.MediaDetails
sizes object____ =
      Object.selectionForCompositeField "sizes" [] (object____) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The width of the mediaItem
-}
width : SelectionSet (Maybe Int) Taco.Object.MediaDetails
width =
      Object.selectionForField "(Maybe Int)" "width" [] (Decode.int |> Decode.nullable)
