-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.MediaItemMeta exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| 
-}
aperture : SelectionSet (Maybe Float) Taco.Object.MediaItemMeta
aperture =
      Object.selectionForField "(Maybe Float)" "aperture" [] (Decode.float |> Decode.nullable)


{-| 
-}
camera : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
camera =
      Object.selectionForField "(Maybe String)" "camera" [] (Decode.string |> Decode.nullable)


{-| 
-}
caption : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
caption =
      Object.selectionForField "(Maybe String)" "caption" [] (Decode.string |> Decode.nullable)


{-| 
-}
copyright : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
copyright =
      Object.selectionForField "(Maybe String)" "copyright" [] (Decode.string |> Decode.nullable)


{-| 
-}
createdTimestamp : SelectionSet (Maybe Int) Taco.Object.MediaItemMeta
createdTimestamp =
      Object.selectionForField "(Maybe Int)" "createdTimestamp" [] (Decode.int |> Decode.nullable)


{-| 
-}
credit : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
credit =
      Object.selectionForField "(Maybe String)" "credit" [] (Decode.string |> Decode.nullable)


{-| 
-}
focalLength : SelectionSet (Maybe Float) Taco.Object.MediaItemMeta
focalLength =
      Object.selectionForField "(Maybe Float)" "focalLength" [] (Decode.float |> Decode.nullable)


{-| 
-}
iso : SelectionSet (Maybe Int) Taco.Object.MediaItemMeta
iso =
      Object.selectionForField "(Maybe Int)" "iso" [] (Decode.int |> Decode.nullable)


{-| 
-}
keywords : SelectionSet (Maybe (List (Maybe String))) Taco.Object.MediaItemMeta
keywords =
      Object.selectionForField "(Maybe (List (Maybe String)))" "keywords" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| 
-}
orientation : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
orientation =
      Object.selectionForField "(Maybe String)" "orientation" [] (Decode.string |> Decode.nullable)


{-| 
-}
shutterSpeed : SelectionSet (Maybe Float) Taco.Object.MediaItemMeta
shutterSpeed =
      Object.selectionForField "(Maybe Float)" "shutterSpeed" [] (Decode.float |> Decode.nullable)


{-| 
-}
title : SelectionSet (Maybe String) Taco.Object.MediaItemMeta
title =
      Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
