-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.MenuItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)
import Taco.Enum.MenuLocationEnum
type alias ChildItemsOptionalArguments = { first : OptionalArgument Int
 , last : OptionalArgument Int
 , after : OptionalArgument String
 , before : OptionalArgument String
 , where_ : OptionalArgument Taco.InputObject.MenuItemToMenuItemConnectionWhereArgs }

{-| Connection between the MenuItem type and the MenuItem type

  - first - The number of items to return after the referenced "after" cursor
  - after - Cursor used along with the "first" argument to reference where in the dataset to get data
  - before - Cursor used along with the "last" argument to reference where in the dataset to get data
  - where_ - Arguments for filtering the connection

-}
childItems : (ChildItemsOptionalArguments -> ChildItemsOptionalArguments)
 -> SelectionSet decodesTo Taco.Object.MenuItemToMenuItemConnection
 -> SelectionSet (Maybe decodesTo) Taco.Object.MenuItem
childItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { first = Absent, last = Absent, after = Absent, before = Absent, where_ = Absent }

        optionalArgs____ =
            [ Argument.optional "first" filledInOptionals____.first (Encode.int), Argument.optional "last" filledInOptionals____.last (Encode.int), Argument.optional "after" filledInOptionals____.after (Encode.string), Argument.optional "before" filledInOptionals____.before (Encode.string), Argument.optional "where" filledInOptionals____.where_ (Taco.InputObject.encodeMenuItemToMenuItemConnectionWhereArgs) ]
                |> List.filterMap identity
    in
      Object.selectionForCompositeField "childItems" optionalArgs____ (object____) (identity >> Decode.nullable)


{-| Connection from MenuItem to it&#039;s connected node
-}
connectedNode : SelectionSet decodesTo Taco.Object.MenuItemToMenuItemLinkableConnectionEdge
 -> SelectionSet (Maybe decodesTo) Taco.Object.MenuItem
connectedNode object____ =
      Object.selectionForCompositeField "connectedNode" [] (object____) (identity >> Decode.nullable)


{-| The object connected to this menu item.
-}
connectedObject : SelectionSet decodesTo Taco.Union.MenuItemObjectUnion
 -> SelectionSet (Maybe decodesTo) Taco.Object.MenuItem
connectedObject object____ =
      Object.selectionForCompositeField "connectedObject" [] (object____) (identity >> Decode.nullable)


{-| Class attribute for the menu item link
-}
cssClasses : SelectionSet (Maybe (List (Maybe String))) Taco.Object.MenuItem
cssClasses =
      Object.selectionForField "(Maybe (List (Maybe String)))" "cssClasses" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The unique identifier stored in the database
-}
databaseId : SelectionSet Int Taco.Object.MenuItem
databaseId =
      Object.selectionForField "Int" "databaseId" [] (Decode.int)


{-| Description of the menu item.
-}
description : SelectionSet (Maybe String) Taco.Object.MenuItem
description =
      Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The globally unique identifier of the nav menu item object.
-}
id : SelectionSet Taco.ScalarCodecs.Id Taco.Object.MenuItem
id =
      Object.selectionForField "ScalarCodecs.Id" "id" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the object is restricted from the current viewer
-}
isRestricted : SelectionSet (Maybe Bool) Taco.Object.MenuItem
isRestricted =
      Object.selectionForField "(Maybe Bool)" "isRestricted" [] (Decode.bool |> Decode.nullable)


{-| Label or title of the menu item.
-}
label : SelectionSet (Maybe String) Taco.Object.MenuItem
label =
      Object.selectionForField "(Maybe String)" "label" [] (Decode.string |> Decode.nullable)


{-| Link relationship (XFN) of the menu item.
-}
linkRelationship : SelectionSet (Maybe String) Taco.Object.MenuItem
linkRelationship =
      Object.selectionForField "(Maybe String)" "linkRelationship" [] (Decode.string |> Decode.nullable)


{-| 
-}
locations : SelectionSet (Maybe (List (Maybe Taco.Enum.MenuLocationEnum.MenuLocationEnum))) Taco.Object.MenuItem
locations =
      Object.selectionForField "(Maybe (List (Maybe Enum.MenuLocationEnum.MenuLocationEnum)))" "locations" [] (Taco.Enum.MenuLocationEnum.decoder |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The Menu a MenuItem is part of
-}
menu : SelectionSet decodesTo Taco.Object.MenuItemToMenuConnectionEdge
 -> SelectionSet (Maybe decodesTo) Taco.Object.MenuItem
menu object____ =
      Object.selectionForCompositeField "menu" [] (object____) (identity >> Decode.nullable)


{-| WP ID of the menu item.
-}
menuItemId : SelectionSet (Maybe Int) Taco.Object.MenuItem
menuItemId =
      Object.selectionForField "(Maybe Int)" "menuItemId" [] (Decode.int |> Decode.nullable)


{-| Menu item order
-}
order : SelectionSet (Maybe Int) Taco.Object.MenuItem
order =
      Object.selectionForField "(Maybe Int)" "order" [] (Decode.int |> Decode.nullable)


{-| The database id of the parent menu item or null if it is the root
-}
parentDatabaseId : SelectionSet (Maybe Int) Taco.Object.MenuItem
parentDatabaseId =
      Object.selectionForField "(Maybe Int)" "parentDatabaseId" [] (Decode.int |> Decode.nullable)


{-| The globally unique identifier of the parent nav menu item object.
-}
parentId : SelectionSet (Maybe Taco.ScalarCodecs.Id) Taco.Object.MenuItem
parentId =
      Object.selectionForField "(Maybe ScalarCodecs.Id)" "parentId" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| Path for the resource. Relative path for internal resources. Absolute path for external resources.
-}
path : SelectionSet String Taco.Object.MenuItem
path =
      Object.selectionForField "String" "path" [] (Decode.string)


{-| Target attribute for the menu item link.
-}
target : SelectionSet (Maybe String) Taco.Object.MenuItem
target =
      Object.selectionForField "(Maybe String)" "target" [] (Decode.string |> Decode.nullable)


{-| Title attribute for the menu item link
-}
title : SelectionSet (Maybe String) Taco.Object.MenuItem
title =
      Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


{-| URL or destination of the menu item.
-}
url : SelectionSet (Maybe String) Taco.Object.MenuItem
url =
      Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
