-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.Plugin exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| Name of the plugin author(s), may also be a company name.
-}
author : SelectionSet (Maybe String) Taco.Object.Plugin
author =
      Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


{-| URI for the related author(s)/company website.
-}
authorUri : SelectionSet (Maybe String) Taco.Object.Plugin
authorUri =
      Object.selectionForField "(Maybe String)" "authorUri" [] (Decode.string |> Decode.nullable)


{-| Description of the plugin.
-}
description : SelectionSet (Maybe String) Taco.Object.Plugin
description =
      Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The globally unique identifier of the plugin object.
-}
id : SelectionSet Taco.ScalarCodecs.Id Taco.Object.Plugin
id =
      Object.selectionForField "ScalarCodecs.Id" "id" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the object is restricted from the current viewer
-}
isRestricted : SelectionSet (Maybe Bool) Taco.Object.Plugin
isRestricted =
      Object.selectionForField "(Maybe Bool)" "isRestricted" [] (Decode.bool |> Decode.nullable)


{-| Display name of the plugin.
-}
name : SelectionSet (Maybe String) Taco.Object.Plugin
name =
      Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Plugin path.
-}
path : SelectionSet (Maybe String) Taco.Object.Plugin
path =
      Object.selectionForField "(Maybe String)" "path" [] (Decode.string |> Decode.nullable)


{-| URI for the plugin website. This is useful for directing users for support requests etc.
-}
pluginUri : SelectionSet (Maybe String) Taco.Object.Plugin
pluginUri =
      Object.selectionForField "(Maybe String)" "pluginUri" [] (Decode.string |> Decode.nullable)


{-| Current version of the plugin.
-}
version : SelectionSet (Maybe String) Taco.Object.Plugin
version =
      Object.selectionForField "(Maybe String)" "version" [] (Decode.string |> Decode.nullable)
