-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.PostTypeLabelDetails exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| Default is ‘Add New’ for both hierarchical and non-hierarchical types.
-}
addNew : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
addNew =
      Object.selectionForField "(Maybe String)" "addNew" [] (Decode.string |> Decode.nullable)


{-| Label for adding a new singular item.
-}
addNewItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
addNewItem =
      Object.selectionForField "(Maybe String)" "addNewItem" [] (Decode.string |> Decode.nullable)


{-| Label to signify all items in a submenu link.
-}
allItems : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
allItems =
      Object.selectionForField "(Maybe String)" "allItems" [] (Decode.string |> Decode.nullable)


{-| Label for archives in nav menus
-}
archives : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
archives =
      Object.selectionForField "(Maybe String)" "archives" [] (Decode.string |> Decode.nullable)


{-| Label for the attributes meta box.
-}
attributes : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
attributes =
      Object.selectionForField "(Maybe String)" "attributes" [] (Decode.string |> Decode.nullable)


{-| Label for editing a singular item.
-}
editItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
editItem =
      Object.selectionForField "(Maybe String)" "editItem" [] (Decode.string |> Decode.nullable)


{-| Label for the Featured Image meta box title.
-}
featuredImage : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
featuredImage =
      Object.selectionForField "(Maybe String)" "featuredImage" [] (Decode.string |> Decode.nullable)


{-| Label for the table views hidden heading.
-}
filterItemsList : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
filterItemsList =
      Object.selectionForField "(Maybe String)" "filterItemsList" [] (Decode.string |> Decode.nullable)


{-| Label for the media frame button.
-}
insertIntoItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
insertIntoItem =
      Object.selectionForField "(Maybe String)" "insertIntoItem" [] (Decode.string |> Decode.nullable)


{-| Label for the table hidden heading.
-}
itemsList : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
itemsList =
      Object.selectionForField "(Maybe String)" "itemsList" [] (Decode.string |> Decode.nullable)


{-| Label for the table pagination hidden heading.
-}
itemsListNavigation : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
itemsListNavigation =
      Object.selectionForField "(Maybe String)" "itemsListNavigation" [] (Decode.string |> Decode.nullable)


{-| Label for the menu name.
-}
menuName : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
menuName =
      Object.selectionForField "(Maybe String)" "menuName" [] (Decode.string |> Decode.nullable)


{-| General name for the post type, usually plural.
-}
name : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
name =
      Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Label for the new item page title.
-}
newItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
newItem =
      Object.selectionForField "(Maybe String)" "newItem" [] (Decode.string |> Decode.nullable)


{-| Label used when no items are found.
-}
notFound : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
notFound =
      Object.selectionForField "(Maybe String)" "notFound" [] (Decode.string |> Decode.nullable)


{-| Label used when no items are in the trash.
-}
notFoundInTrash : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
notFoundInTrash =
      Object.selectionForField "(Maybe String)" "notFoundInTrash" [] (Decode.string |> Decode.nullable)


{-| Label used to prefix parents of hierarchical items.
-}
parentItemColon : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
parentItemColon =
      Object.selectionForField "(Maybe String)" "parentItemColon" [] (Decode.string |> Decode.nullable)


{-| Label for removing the featured image.
-}
removeFeaturedImage : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
removeFeaturedImage =
      Object.selectionForField "(Maybe String)" "removeFeaturedImage" [] (Decode.string |> Decode.nullable)


{-| Label for searching plural items.
-}
searchItems : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
searchItems =
      Object.selectionForField "(Maybe String)" "searchItems" [] (Decode.string |> Decode.nullable)


{-| Label for setting the featured image.
-}
setFeaturedImage : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
setFeaturedImage =
      Object.selectionForField "(Maybe String)" "setFeaturedImage" [] (Decode.string |> Decode.nullable)


{-| Name for one object of this post type.
-}
singularName : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
singularName =
      Object.selectionForField "(Maybe String)" "singularName" [] (Decode.string |> Decode.nullable)


{-| Label for the media frame filter.
-}
uploadedToThisItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
uploadedToThisItem =
      Object.selectionForField "(Maybe String)" "uploadedToThisItem" [] (Decode.string |> Decode.nullable)


{-| Label in the media frame for using a featured image.
-}
useFeaturedImage : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
useFeaturedImage =
      Object.selectionForField "(Maybe String)" "useFeaturedImage" [] (Decode.string |> Decode.nullable)


{-| Label for viewing a singular item.
-}
viewItem : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
viewItem =
      Object.selectionForField "(Maybe String)" "viewItem" [] (Decode.string |> Decode.nullable)


{-| Label for viewing post type archives.
-}
viewItems : SelectionSet (Maybe String) Taco.Object.PostTypeLabelDetails
viewItems =
      Object.selectionForField "(Maybe String)" "viewItems" [] (Decode.string |> Decode.nullable)
