-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object.Taxonomy exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

type alias ConnectedContentTypesOptionalArguments = { first : OptionalArgument Int
 , last : OptionalArgument Int
 , after : OptionalArgument String
 , before : OptionalArgument String }

{-| List of Content Types associated with the Taxonomy

  - first - The number of items to return after the referenced "after" cursor
  - after - Cursor used along with the "first" argument to reference where in the dataset to get data
  - before - Cursor used along with the "last" argument to reference where in the dataset to get data

-}
connectedContentTypes : (ConnectedContentTypesOptionalArguments -> ConnectedContentTypesOptionalArguments)
 -> SelectionSet decodesTo Taco.Object.TaxonomyToContentTypeConnection
 -> SelectionSet (Maybe decodesTo) Taco.Object.Taxonomy
connectedContentTypes fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { first = Absent, last = Absent, after = Absent, before = Absent }

        optionalArgs____ =
            [ Argument.optional "first" filledInOptionals____.first (Encode.int), Argument.optional "last" filledInOptionals____.last (Encode.int), Argument.optional "after" filledInOptionals____.after (Encode.string), Argument.optional "before" filledInOptionals____.before (Encode.string) ]
                |> List.filterMap identity
    in
      Object.selectionForCompositeField "connectedContentTypes" optionalArgs____ (object____) (identity >> Decode.nullable)


{-| Description of the taxonomy. This field is equivalent to WP_Taxonomy-&gt;description
-}
description : SelectionSet (Maybe String) Taco.Object.Taxonomy
description =
      Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The plural name of the post type within the GraphQL Schema.
-}
graphqlPluralName : SelectionSet (Maybe String) Taco.Object.Taxonomy
graphqlPluralName =
      Object.selectionForField "(Maybe String)" "graphqlPluralName" [] (Decode.string |> Decode.nullable)


{-| The singular name of the post type within the GraphQL Schema.
-}
graphqlSingleName : SelectionSet (Maybe String) Taco.Object.Taxonomy
graphqlSingleName =
      Object.selectionForField "(Maybe String)" "graphqlSingleName" [] (Decode.string |> Decode.nullable)


{-| Whether the taxonomy is hierarchical
-}
hierarchical : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
hierarchical =
      Object.selectionForField "(Maybe Bool)" "hierarchical" [] (Decode.bool |> Decode.nullable)


{-| The globally unique identifier of the taxonomy object.
-}
id : SelectionSet Taco.ScalarCodecs.Id Taco.Object.Taxonomy
id =
      Object.selectionForField "ScalarCodecs.Id" "id" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the object is restricted from the current viewer
-}
isRestricted : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
isRestricted =
      Object.selectionForField "(Maybe Bool)" "isRestricted" [] (Decode.bool |> Decode.nullable)


{-| Name of the taxonomy shown in the menu. Usually plural.
-}
label : SelectionSet (Maybe String) Taco.Object.Taxonomy
label =
      Object.selectionForField "(Maybe String)" "label" [] (Decode.string |> Decode.nullable)


{-| The display name of the taxonomy. This field is equivalent to WP_Taxonomy-&gt;label
-}
name : SelectionSet (Maybe String) Taco.Object.Taxonomy
name =
      Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Whether the taxonomy is publicly queryable
-}
public : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
public =
      Object.selectionForField "(Maybe Bool)" "public" [] (Decode.bool |> Decode.nullable)


{-| Name of content type to diplay in REST API &quot;wp/v2&quot; namespace.
-}
restBase : SelectionSet (Maybe String) Taco.Object.Taxonomy
restBase =
      Object.selectionForField "(Maybe String)" "restBase" [] (Decode.string |> Decode.nullable)


{-| The REST Controller class assigned to handling this content type.
-}
restControllerClass : SelectionSet (Maybe String) Taco.Object.Taxonomy
restControllerClass =
      Object.selectionForField "(Maybe String)" "restControllerClass" [] (Decode.string |> Decode.nullable)


{-| Whether to show the taxonomy as part of a tag cloud widget. This field is equivalent to WP_Taxonomy-&gt;show_tagcloud
-}
showCloud : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showCloud =
      Object.selectionForField "(Maybe Bool)" "showCloud" [] (Decode.bool |> Decode.nullable)


{-| Whether to display a column for the taxonomy on its post type listing screens.
-}
showInAdminColumn : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInAdminColumn =
      Object.selectionForField "(Maybe Bool)" "showInAdminColumn" [] (Decode.bool |> Decode.nullable)


{-| Whether to add the post type to the GraphQL Schema.
-}
showInGraphql : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInGraphql =
      Object.selectionForField "(Maybe Bool)" "showInGraphql" [] (Decode.bool |> Decode.nullable)


{-| Whether to show the taxonomy in the admin menu
-}
showInMenu : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInMenu =
      Object.selectionForField "(Maybe Bool)" "showInMenu" [] (Decode.bool |> Decode.nullable)


{-| Whether the taxonomy is available for selection in navigation menus.
-}
showInNavMenus : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInNavMenus =
      Object.selectionForField "(Maybe Bool)" "showInNavMenus" [] (Decode.bool |> Decode.nullable)


{-| Whether to show the taxonomy in the quick/bulk edit panel.
-}
showInQuickEdit : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInQuickEdit =
      Object.selectionForField "(Maybe Bool)" "showInQuickEdit" [] (Decode.bool |> Decode.nullable)


{-| Whether to add the post type route in the REST API &quot;wp/v2&quot; namespace.
-}
showInRest : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showInRest =
      Object.selectionForField "(Maybe Bool)" "showInRest" [] (Decode.bool |> Decode.nullable)


{-| Whether to generate and allow a UI for managing terms in this taxonomy in the admin
-}
showUi : SelectionSet (Maybe Bool) Taco.Object.Taxonomy
showUi =
      Object.selectionForField "(Maybe Bool)" "showUi" [] (Decode.bool |> Decode.nullable)
