-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Interface.Commenter exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


type alias Fragments decodesTo =
    {
    onUser : SelectionSet decodesTo Taco.Object.User,
 onCommentAuthor : SelectionSet decodesTo Taco.Object.CommentAuthor
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
      Fragments decodesTo
      -> SelectionSet decodesTo Taco.Interface.Commenter
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [
         Object.buildFragment "User" selections____.onUser,
 Object.buildFragment "CommentAuthor" selections____.onCommentAuthor
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    {
      onUser = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing),
 onCommentAuthor = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }
{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet Int Taco.Interface.Commenter
databaseId =
      Object.selectionForField "Int" "databaseId" [] (Decode.int)


{-| The email address of the author of a comment.
-}
email : SelectionSet (Maybe String) Taco.Interface.Commenter
email =
      Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


{-| The globally unique identifier for the comment author.
-}
id : SelectionSet Taco.ScalarCodecs.Id Taco.Interface.Commenter
id =
      Object.selectionForField "ScalarCodecs.Id" "id" [] (Taco.ScalarCodecs.codecs |> Taco.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the author information is considered restricted. (not fully public)
-}
isRestricted : SelectionSet (Maybe Bool) Taco.Interface.Commenter
isRestricted =
      Object.selectionForField "(Maybe Bool)" "isRestricted" [] (Decode.bool |> Decode.nullable)


{-| The name of the author of a comment.
-}
name : SelectionSet (Maybe String) Taco.Interface.Commenter
name =
      Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The url of the author of a comment.
-}
url : SelectionSet (Maybe String) Taco.Interface.Commenter
url =
      Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
