-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Interface.NodeWithTrackbacks exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


type alias Fragments decodesTo =
    {
    onPost : SelectionSet decodesTo Taco.Object.Post
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
      Fragments decodesTo
      -> SelectionSet decodesTo Taco.Interface.NodeWithTrackbacks
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [
         Object.buildFragment "Post" selections____.onPost
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    {
      onPost = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }
{-| Whether the pings are open or closed for this particular post.
-}
pingStatus : SelectionSet (Maybe String) Taco.Interface.NodeWithTrackbacks
pingStatus =
      Object.selectionForField "(Maybe String)" "pingStatus" [] (Decode.string |> Decode.nullable)


{-| URLs that have been pinged.
-}
pinged : SelectionSet (Maybe (List (Maybe String))) Taco.Interface.NodeWithTrackbacks
pinged =
      Object.selectionForField "(Maybe (List (Maybe String)))" "pinged" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| URLs queued to be pinged.
-}
toPing : SelectionSet (Maybe (List (Maybe String))) Taco.Interface.NodeWithTrackbacks
toPing =
      Object.selectionForField "(Maybe (List (Maybe String)))" "toPing" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)
