-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Interface.NodeWithRevisions exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


type alias Fragments decodesTo =
    {
    onPage : SelectionSet decodesTo Taco.Object.Page,
 onPost : SelectionSet decodesTo Taco.Object.Post
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
      Fragments decodesTo
      -> SelectionSet decodesTo Taco.Interface.NodeWithRevisions
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [
         Object.buildFragment "Page" selections____.onPage,
 Object.buildFragment "Post" selections____.onPost
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    {
      onPage = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing),
 onPost = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }
{-| True if the node is a revision of another node
-}
isRevision : SelectionSet (Maybe Bool) Taco.Interface.NodeWithRevisions
isRevision =
      Object.selectionForField "(Maybe Bool)" "isRevision" [] (Decode.bool |> Decode.nullable)


{-| If the current node is a revision, this field exposes the node this is a revision of. Returns null if the node is not a revision of another node.
-}
revisionOf : SelectionSet decodesTo Taco.Object.NodeWithRevisionsToContentNodeConnectionEdge
 -> SelectionSet (Maybe decodesTo) Taco.Interface.NodeWithRevisions
revisionOf object____ =
      Object.selectionForCompositeField "revisionOf" [] (object____) (identity >> Decode.nullable)
