-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Interface exposing (..)


type Commenter
    = Commenter


type ContentNode
    = ContentNode


type ContentTemplate
    = ContentTemplate


type DatabaseIdentifier
    = DatabaseIdentifier


type EnqueuedAsset
    = EnqueuedAsset


type HierarchicalContentNode
    = HierarchicalContentNode


type HierarchicalTermNode
    = HierarchicalTermNode


type MenuItemLinkable
    = MenuItemLinkable


type Node
    = Node


type NodeWithAuthor
    = NodeWithAuthor


type NodeWithComments
    = NodeWithComments


type NodeWithContentEditor
    = NodeWithContentEditor


type NodeWithExcerpt
    = NodeWithExcerpt


type NodeWithFeaturedImage
    = NodeWithFeaturedImage


type NodeWithPageAttributes
    = NodeWithPageAttributes


type NodeWithRevisions
    = NodeWithRevisions


type NodeWithTemplate
    = NodeWithTemplate


type NodeWithTitle
    = NodeWithTitle


type NodeWithTrackbacks
    = NodeWithTrackbacks


type TermNode
    = TermNode


type UniformResourceIdentifiable
    = UniformResourceIdentifiable
