-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Taco.Object
import Taco.Interface
import Taco.Union
import Taco.Scalar
import Taco.InputObject
import Taco.ScalarCodecs
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Json.Decode as Decode exposing (Decoder)
import Graphql.Internal.Encode as Encode exposing (Value)

type alias UpdateCategoryRequiredArguments = { input : Taco.InputObject.UpdateCategoryInput }

{-| The payload for the UpdateCategory mutation

  - input - Input for the UpdateCategory mutation

-}
updateCategory : UpdateCategoryRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateCategoryPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateCategory requiredArgs____ object____ =
      Object.selectionForCompositeField "updateCategory" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateCategoryInput) ] (object____) (identity >> Decode.nullable)


type alias UpdatePostFormatRequiredArguments = { input : Taco.InputObject.UpdatePostFormatInput }

{-| The payload for the UpdatePostFormat mutation

  - input - Input for the UpdatePostFormat mutation

-}
updatePostFormat : UpdatePostFormatRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdatePostFormatPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updatePostFormat requiredArgs____ object____ =
      Object.selectionForCompositeField "updatePostFormat" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdatePostFormatInput) ] (object____) (identity >> Decode.nullable)


type alias UpdateTagRequiredArguments = { input : Taco.InputObject.UpdateTagInput }

{-| The payload for the UpdateTag mutation

  - input - Input for the UpdateTag mutation

-}
updateTag : UpdateTagRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateTagPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateTag requiredArgs____ object____ =
      Object.selectionForCompositeField "updateTag" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateTagInput) ] (object____) (identity >> Decode.nullable)


type alias CreateCategoryRequiredArguments = { input : Taco.InputObject.CreateCategoryInput }

{-| The payload for the createCategory mutation

  - input - Input for the createCategory mutation

-}
createCategory : CreateCategoryRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreateCategoryPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createCategory requiredArgs____ object____ =
      Object.selectionForCompositeField "createCategory" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreateCategoryInput) ] (object____) (identity >> Decode.nullable)


type alias CreateCommentRequiredArguments = { input : Taco.InputObject.CreateCommentInput }

{-| The payload for the createComment mutation

  - input - Input for the createComment mutation

-}
createComment : CreateCommentRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreateCommentPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createComment requiredArgs____ object____ =
      Object.selectionForCompositeField "createComment" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreateCommentInput) ] (object____) (identity >> Decode.nullable)


type alias CreateMediaItemRequiredArguments = { input : Taco.InputObject.CreateMediaItemInput }

{-| The payload for the createMediaItem mutation

  - input - Input for the createMediaItem mutation

-}
createMediaItem : CreateMediaItemRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreateMediaItemPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createMediaItem requiredArgs____ object____ =
      Object.selectionForCompositeField "createMediaItem" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreateMediaItemInput) ] (object____) (identity >> Decode.nullable)


type alias CreatePageRequiredArguments = { input : Taco.InputObject.CreatePageInput }

{-| The payload for the createPage mutation

  - input - Input for the createPage mutation

-}
createPage : CreatePageRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreatePagePayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createPage requiredArgs____ object____ =
      Object.selectionForCompositeField "createPage" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreatePageInput) ] (object____) (identity >> Decode.nullable)


type alias CreatePostRequiredArguments = { input : Taco.InputObject.CreatePostInput }

{-| The payload for the createPost mutation

  - input - Input for the createPost mutation

-}
createPost : CreatePostRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreatePostPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createPost requiredArgs____ object____ =
      Object.selectionForCompositeField "createPost" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreatePostInput) ] (object____) (identity >> Decode.nullable)


type alias CreatePostFormatRequiredArguments = { input : Taco.InputObject.CreatePostFormatInput }

{-| The payload for the createPostFormat mutation

  - input - Input for the createPostFormat mutation

-}
createPostFormat : CreatePostFormatRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreatePostFormatPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createPostFormat requiredArgs____ object____ =
      Object.selectionForCompositeField "createPostFormat" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreatePostFormatInput) ] (object____) (identity >> Decode.nullable)


type alias CreateTagRequiredArguments = { input : Taco.InputObject.CreateTagInput }

{-| The payload for the createTag mutation

  - input - Input for the createTag mutation

-}
createTag : CreateTagRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreateTagPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createTag requiredArgs____ object____ =
      Object.selectionForCompositeField "createTag" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreateTagInput) ] (object____) (identity >> Decode.nullable)


type alias CreateUserRequiredArguments = { input : Taco.InputObject.CreateUserInput }

{-| The payload for the createUser mutation

  - input - Input for the createUser mutation

-}
createUser : CreateUserRequiredArguments
 -> SelectionSet decodesTo Taco.Object.CreateUserPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
createUser requiredArgs____ object____ =
      Object.selectionForCompositeField "createUser" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeCreateUserInput) ] (object____) (identity >> Decode.nullable)


type alias DeleteCategoryRequiredArguments = { input : Taco.InputObject.DeleteCategoryInput }

{-| The payload for the deleteCategory mutation

  - input - Input for the deleteCategory mutation

-}
deleteCategory : DeleteCategoryRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeleteCategoryPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deleteCategory requiredArgs____ object____ =
      Object.selectionForCompositeField "deleteCategory" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeleteCategoryInput) ] (object____) (identity >> Decode.nullable)


type alias DeleteCommentRequiredArguments = { input : Taco.InputObject.DeleteCommentInput }

{-| The payload for the deleteComment mutation

  - input - Input for the deleteComment mutation

-}
deleteComment : DeleteCommentRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeleteCommentPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deleteComment requiredArgs____ object____ =
      Object.selectionForCompositeField "deleteComment" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeleteCommentInput) ] (object____) (identity >> Decode.nullable)


type alias DeleteMediaItemRequiredArguments = { input : Taco.InputObject.DeleteMediaItemInput }

{-| The payload for the deleteMediaItem mutation

  - input - Input for the deleteMediaItem mutation

-}
deleteMediaItem : DeleteMediaItemRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeleteMediaItemPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deleteMediaItem requiredArgs____ object____ =
      Object.selectionForCompositeField "deleteMediaItem" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeleteMediaItemInput) ] (object____) (identity >> Decode.nullable)


type alias DeletePageRequiredArguments = { input : Taco.InputObject.DeletePageInput }

{-| The payload for the deletePage mutation

  - input - Input for the deletePage mutation

-}
deletePage : DeletePageRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeletePagePayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deletePage requiredArgs____ object____ =
      Object.selectionForCompositeField "deletePage" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeletePageInput) ] (object____) (identity >> Decode.nullable)


type alias DeletePostRequiredArguments = { input : Taco.InputObject.DeletePostInput }

{-| The payload for the deletePost mutation

  - input - Input for the deletePost mutation

-}
deletePost : DeletePostRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeletePostPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deletePost requiredArgs____ object____ =
      Object.selectionForCompositeField "deletePost" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeletePostInput) ] (object____) (identity >> Decode.nullable)


type alias DeletePostFormatRequiredArguments = { input : Taco.InputObject.DeletePostFormatInput }

{-| The payload for the deletePostFormat mutation

  - input - Input for the deletePostFormat mutation

-}
deletePostFormat : DeletePostFormatRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeletePostFormatPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deletePostFormat requiredArgs____ object____ =
      Object.selectionForCompositeField "deletePostFormat" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeletePostFormatInput) ] (object____) (identity >> Decode.nullable)


type alias DeleteTagRequiredArguments = { input : Taco.InputObject.DeleteTagInput }

{-| The payload for the deleteTag mutation

  - input - Input for the deleteTag mutation

-}
deleteTag : DeleteTagRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeleteTagPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deleteTag requiredArgs____ object____ =
      Object.selectionForCompositeField "deleteTag" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeleteTagInput) ] (object____) (identity >> Decode.nullable)


type alias DeleteUserRequiredArguments = { input : Taco.InputObject.DeleteUserInput }

{-| The payload for the deleteUser mutation

  - input - Input for the deleteUser mutation

-}
deleteUser : DeleteUserRequiredArguments
 -> SelectionSet decodesTo Taco.Object.DeleteUserPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
deleteUser requiredArgs____ object____ =
      Object.selectionForCompositeField "deleteUser" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeDeleteUserInput) ] (object____) (identity >> Decode.nullable)


type alias IncreaseCountOptionalArguments = { count : OptionalArgument Int }

{-| 

  - count - The count to increase

-}
increaseCount : (IncreaseCountOptionalArguments -> IncreaseCountOptionalArguments)
 -> SelectionSet (Maybe Int) RootMutation
increaseCount fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { count = Absent }

        optionalArgs____ =
            [ Argument.optional "count" filledInOptionals____.count (Encode.int) ]
                |> List.filterMap identity
    in
      Object.selectionForField "(Maybe Int)" "increaseCount" optionalArgs____ (Decode.int |> Decode.nullable)


type alias RegisterUserRequiredArguments = { input : Taco.InputObject.RegisterUserInput }

{-| The payload for the registerUser mutation

  - input - Input for the registerUser mutation

-}
registerUser : RegisterUserRequiredArguments
 -> SelectionSet decodesTo Taco.Object.RegisterUserPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
registerUser requiredArgs____ object____ =
      Object.selectionForCompositeField "registerUser" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeRegisterUserInput) ] (object____) (identity >> Decode.nullable)


type alias ResetUserPasswordRequiredArguments = { input : Taco.InputObject.ResetUserPasswordInput }

{-| The payload for the resetUserPassword mutation

  - input - Input for the resetUserPassword mutation

-}
resetUserPassword : ResetUserPasswordRequiredArguments
 -> SelectionSet decodesTo Taco.Object.ResetUserPasswordPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
resetUserPassword requiredArgs____ object____ =
      Object.selectionForCompositeField "resetUserPassword" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeResetUserPasswordInput) ] (object____) (identity >> Decode.nullable)


type alias RestoreCommentRequiredArguments = { input : Taco.InputObject.RestoreCommentInput }

{-| The payload for the restoreComment mutation

  - input - Input for the restoreComment mutation

-}
restoreComment : RestoreCommentRequiredArguments
 -> SelectionSet decodesTo Taco.Object.RestoreCommentPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
restoreComment requiredArgs____ object____ =
      Object.selectionForCompositeField "restoreComment" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeRestoreCommentInput) ] (object____) (identity >> Decode.nullable)


type alias SendPasswordResetEmailRequiredArguments = { input : Taco.InputObject.SendPasswordResetEmailInput }

{-| The payload for the sendPasswordResetEmail mutation

  - input - Input for the sendPasswordResetEmail mutation

-}
sendPasswordResetEmail : SendPasswordResetEmailRequiredArguments
 -> SelectionSet decodesTo Taco.Object.SendPasswordResetEmailPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
sendPasswordResetEmail requiredArgs____ object____ =
      Object.selectionForCompositeField "sendPasswordResetEmail" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeSendPasswordResetEmailInput) ] (object____) (identity >> Decode.nullable)


type alias UpdateCommentRequiredArguments = { input : Taco.InputObject.UpdateCommentInput }

{-| The payload for the updateComment mutation

  - input - Input for the updateComment mutation

-}
updateComment : UpdateCommentRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateCommentPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateComment requiredArgs____ object____ =
      Object.selectionForCompositeField "updateComment" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateCommentInput) ] (object____) (identity >> Decode.nullable)


type alias UpdateMediaItemRequiredArguments = { input : Taco.InputObject.UpdateMediaItemInput }

{-| The payload for the updateMediaItem mutation

  - input - Input for the updateMediaItem mutation

-}
updateMediaItem : UpdateMediaItemRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateMediaItemPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateMediaItem requiredArgs____ object____ =
      Object.selectionForCompositeField "updateMediaItem" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateMediaItemInput) ] (object____) (identity >> Decode.nullable)


type alias UpdatePageRequiredArguments = { input : Taco.InputObject.UpdatePageInput }

{-| The payload for the updatePage mutation

  - input - Input for the updatePage mutation

-}
updatePage : UpdatePageRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdatePagePayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updatePage requiredArgs____ object____ =
      Object.selectionForCompositeField "updatePage" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdatePageInput) ] (object____) (identity >> Decode.nullable)


type alias UpdatePostRequiredArguments = { input : Taco.InputObject.UpdatePostInput }

{-| The payload for the updatePost mutation

  - input - Input for the updatePost mutation

-}
updatePost : UpdatePostRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdatePostPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updatePost requiredArgs____ object____ =
      Object.selectionForCompositeField "updatePost" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdatePostInput) ] (object____) (identity >> Decode.nullable)


type alias UpdateSettingsRequiredArguments = { input : Taco.InputObject.UpdateSettingsInput }

{-| The payload for the updateSettings mutation

  - input - Input for the updateSettings mutation

-}
updateSettings : UpdateSettingsRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateSettingsPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateSettings requiredArgs____ object____ =
      Object.selectionForCompositeField "updateSettings" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateSettingsInput) ] (object____) (identity >> Decode.nullable)


type alias UpdateUserRequiredArguments = { input : Taco.InputObject.UpdateUserInput }

{-| The payload for the updateUser mutation

  - input - Input for the updateUser mutation

-}
updateUser : UpdateUserRequiredArguments
 -> SelectionSet decodesTo Taco.Object.UpdateUserPayload
 -> SelectionSet (Maybe decodesTo) RootMutation
updateUser requiredArgs____ object____ =
      Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs____.input (Taco.InputObject.encodeUpdateUserInput) ] (object____) (identity >> Decode.nullable)
