-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Object exposing (..)


type Avatar
    = Avatar


type Category
    = Category


type CategoryToAncestorsCategoryConnection
    = CategoryToAncestorsCategoryConnection


type CategoryToAncestorsCategoryConnectionEdge
    = CategoryToAncestorsCategoryConnectionEdge


type CategoryToCategoryConnection
    = CategoryToCategoryConnection


type CategoryToCategoryConnectionEdge
    = CategoryToCategoryConnectionEdge


type CategoryToContentNodeConnection
    = CategoryToContentNodeConnection


type CategoryToContentNodeConnectionEdge
    = CategoryToContentNodeConnectionEdge


type CategoryToParentCategoryConnectionEdge
    = CategoryToParentCategoryConnectionEdge


type CategoryToPostConnection
    = CategoryToPostConnection


type CategoryToPostConnectionEdge
    = CategoryToPostConnectionEdge


type CategoryToTaxonomyConnectionEdge
    = CategoryToTaxonomyConnectionEdge


type Comment
    = Comment


type CommentAuthor
    = CommentAuthor


type CommentToCommentConnection
    = CommentToCommentConnection


type CommentToCommentConnectionEdge
    = CommentToCommentConnectionEdge


type CommentToCommenterConnectionEdge
    = CommentToCommenterConnectionEdge


type CommentToContentNodeConnectionEdge
    = CommentToContentNodeConnectionEdge


type CommentToParentCommentConnectionEdge
    = CommentToParentCommentConnectionEdge


type ContentNodeToContentTypeConnectionEdge
    = ContentNodeToContentTypeConnectionEdge


type ContentNodeToEditLastConnectionEdge
    = ContentNodeToEditLastConnectionEdge


type ContentNodeToEditLockConnectionEdge
    = ContentNodeToEditLockConnectionEdge


type ContentNodeToEnqueuedScriptConnection
    = ContentNodeToEnqueuedScriptConnection


type ContentNodeToEnqueuedScriptConnectionEdge
    = ContentNodeToEnqueuedScriptConnectionEdge


type ContentNodeToEnqueuedStylesheetConnection
    = ContentNodeToEnqueuedStylesheetConnection


type ContentNodeToEnqueuedStylesheetConnectionEdge
    = ContentNodeToEnqueuedStylesheetConnectionEdge


type ContentType
    = ContentType


type ContentTypeToContentNodeConnection
    = ContentTypeToContentNodeConnection


type ContentTypeToContentNodeConnectionEdge
    = ContentTypeToContentNodeConnectionEdge


type ContentTypeToTaxonomyConnection
    = ContentTypeToTaxonomyConnection


type ContentTypeToTaxonomyConnectionEdge
    = ContentTypeToTaxonomyConnectionEdge


type CreateCategoryPayload
    = CreateCategoryPayload


type CreateCommentPayload
    = CreateCommentPayload


type CreateMediaItemPayload
    = CreateMediaItemPayload


type CreatePagePayload
    = CreatePagePayload


type CreatePostFormatPayload
    = CreatePostFormatPayload


type CreatePostPayload
    = CreatePostPayload


type CreateTagPayload
    = CreateTagPayload


type CreateUserPayload
    = CreateUserPayload


type DeleteCategoryPayload
    = DeleteCategoryPayload


type DeleteCommentPayload
    = DeleteCommentPayload


type DeleteMediaItemPayload
    = DeleteMediaItemPayload


type DeletePagePayload
    = DeletePagePayload


type DeletePostFormatPayload
    = DeletePostFormatPayload


type DeletePostPayload
    = DeletePostPayload


type DeleteTagPayload
    = DeleteTagPayload


type DeleteUserPayload
    = DeleteUserPayload


type DiscussionSettings
    = DiscussionSettings


type EnqueuedScript
    = EnqueuedScript


type EnqueuedStylesheet
    = EnqueuedStylesheet


type GeneralSettings
    = GeneralSettings


type HierarchicalContentNodeToContentNodeAncestorsConnection
    = HierarchicalContentNodeToContentNodeAncestorsConnection


type HierarchicalContentNodeToContentNodeAncestorsConnectionEdge
    = HierarchicalContentNodeToContentNodeAncestorsConnectionEdge


type HierarchicalContentNodeToContentNodeChildrenConnection
    = HierarchicalContentNodeToContentNodeChildrenConnection


type HierarchicalContentNodeToContentNodeChildrenConnectionEdge
    = HierarchicalContentNodeToContentNodeChildrenConnectionEdge


type HierarchicalContentNodeToParentContentNodeConnectionEdge
    = HierarchicalContentNodeToParentContentNodeConnectionEdge


type MediaDetails
    = MediaDetails


type MediaItem
    = MediaItem


type MediaItemMeta
    = MediaItemMeta


type MediaItemToCommentConnection
    = MediaItemToCommentConnection


type MediaItemToCommentConnectionEdge
    = MediaItemToCommentConnectionEdge


type MediaSize
    = MediaSize


type Menu
    = Menu


type MenuItem
    = MenuItem


type MenuItemToMenuConnectionEdge
    = MenuItemToMenuConnectionEdge


type MenuItemToMenuItemConnection
    = MenuItemToMenuItemConnection


type MenuItemToMenuItemConnectionEdge
    = MenuItemToMenuItemConnectionEdge


type MenuItemToMenuItemLinkableConnectionEdge
    = MenuItemToMenuItemLinkableConnectionEdge


type MenuToMenuItemConnection
    = MenuToMenuItemConnection


type MenuToMenuItemConnectionEdge
    = MenuToMenuItemConnectionEdge


type NodeWithAuthorToUserConnectionEdge
    = NodeWithAuthorToUserConnectionEdge


type NodeWithFeaturedImageToMediaItemConnectionEdge
    = NodeWithFeaturedImageToMediaItemConnectionEdge


type NodeWithRevisionsToContentNodeConnectionEdge
    = NodeWithRevisionsToContentNodeConnectionEdge


type Page
    = Page


type PageToCommentConnection
    = PageToCommentConnection


type PageToCommentConnectionEdge
    = PageToCommentConnectionEdge


type PageToPreviewConnectionEdge
    = PageToPreviewConnectionEdge


type PageToRevisionConnection
    = PageToRevisionConnection


type PageToRevisionConnectionEdge
    = PageToRevisionConnectionEdge


type Plugin
    = Plugin


type Post
    = Post


type PostFormat
    = PostFormat


type PostFormatToContentNodeConnection
    = PostFormatToContentNodeConnection


type PostFormatToContentNodeConnectionEdge
    = PostFormatToContentNodeConnectionEdge


type PostFormatToPostConnection
    = PostFormatToPostConnection


type PostFormatToPostConnectionEdge
    = PostFormatToPostConnectionEdge


type PostFormatToTaxonomyConnectionEdge
    = PostFormatToTaxonomyConnectionEdge


type PostToCategoryConnection
    = PostToCategoryConnection


type PostToCategoryConnectionEdge
    = PostToCategoryConnectionEdge


type PostToCommentConnection
    = PostToCommentConnection


type PostToCommentConnectionEdge
    = PostToCommentConnectionEdge


type PostToPostFormatConnection
    = PostToPostFormatConnection


type PostToPostFormatConnectionEdge
    = PostToPostFormatConnectionEdge


type PostToPreviewConnectionEdge
    = PostToPreviewConnectionEdge


type PostToRevisionConnection
    = PostToRevisionConnection


type PostToRevisionConnectionEdge
    = PostToRevisionConnectionEdge


type PostToTagConnection
    = PostToTagConnection


type PostToTagConnectionEdge
    = PostToTagConnectionEdge


type PostToTermNodeConnection
    = PostToTermNodeConnection


type PostToTermNodeConnectionEdge
    = PostToTermNodeConnectionEdge


type PostTypeLabelDetails
    = PostTypeLabelDetails


type ReadingSettings
    = ReadingSettings


type RegisterUserPayload
    = RegisterUserPayload


type ResetUserPasswordPayload
    = ResetUserPasswordPayload


type RestoreCommentPayload
    = RestoreCommentPayload


type RootQueryToCategoryConnection
    = RootQueryToCategoryConnection


type RootQueryToCategoryConnectionEdge
    = RootQueryToCategoryConnectionEdge


type RootQueryToCommentConnection
    = RootQueryToCommentConnection


type RootQueryToCommentConnectionEdge
    = RootQueryToCommentConnectionEdge


type RootQueryToContentNodeConnection
    = RootQueryToContentNodeConnection


type RootQueryToContentNodeConnectionEdge
    = RootQueryToContentNodeConnectionEdge


type RootQueryToContentRevisionUnionConnection
    = RootQueryToContentRevisionUnionConnection


type RootQueryToContentRevisionUnionConnectionEdge
    = RootQueryToContentRevisionUnionConnectionEdge


type RootQueryToContentTypeConnection
    = RootQueryToContentTypeConnection


type RootQueryToContentTypeConnectionEdge
    = RootQueryToContentTypeConnectionEdge


type RootQueryToEnqueuedScriptConnection
    = RootQueryToEnqueuedScriptConnection


type RootQueryToEnqueuedScriptConnectionEdge
    = RootQueryToEnqueuedScriptConnectionEdge


type RootQueryToEnqueuedStylesheetConnection
    = RootQueryToEnqueuedStylesheetConnection


type RootQueryToEnqueuedStylesheetConnectionEdge
    = RootQueryToEnqueuedStylesheetConnectionEdge


type RootQueryToMediaItemConnection
    = RootQueryToMediaItemConnection


type RootQueryToMediaItemConnectionEdge
    = RootQueryToMediaItemConnectionEdge


type RootQueryToMenuConnection
    = RootQueryToMenuConnection


type RootQueryToMenuConnectionEdge
    = RootQueryToMenuConnectionEdge


type RootQueryToMenuItemConnection
    = RootQueryToMenuItemConnection


type RootQueryToMenuItemConnectionEdge
    = RootQueryToMenuItemConnectionEdge


type RootQueryToPageConnection
    = RootQueryToPageConnection


type RootQueryToPageConnectionEdge
    = RootQueryToPageConnectionEdge


type RootQueryToPluginConnection
    = RootQueryToPluginConnection


type RootQueryToPluginConnectionEdge
    = RootQueryToPluginConnectionEdge


type RootQueryToPostConnection
    = RootQueryToPostConnection


type RootQueryToPostConnectionEdge
    = RootQueryToPostConnectionEdge


type RootQueryToPostFormatConnection
    = RootQueryToPostFormatConnection


type RootQueryToPostFormatConnectionEdge
    = RootQueryToPostFormatConnectionEdge


type RootQueryToTagConnection
    = RootQueryToTagConnection


type RootQueryToTagConnectionEdge
    = RootQueryToTagConnectionEdge


type RootQueryToTaxonomyConnection
    = RootQueryToTaxonomyConnection


type RootQueryToTaxonomyConnectionEdge
    = RootQueryToTaxonomyConnectionEdge


type RootQueryToTermNodeConnection
    = RootQueryToTermNodeConnection


type RootQueryToTermNodeConnectionEdge
    = RootQueryToTermNodeConnectionEdge


type RootQueryToThemeConnection
    = RootQueryToThemeConnection


type RootQueryToThemeConnectionEdge
    = RootQueryToThemeConnectionEdge


type RootQueryToUserConnection
    = RootQueryToUserConnection


type RootQueryToUserConnectionEdge
    = RootQueryToUserConnectionEdge


type RootQueryToUserRoleConnection
    = RootQueryToUserRoleConnection


type RootQueryToUserRoleConnectionEdge
    = RootQueryToUserRoleConnectionEdge


type SendPasswordResetEmailPayload
    = SendPasswordResetEmailPayload


type Settings
    = Settings


type Tag
    = Tag


type TagToContentNodeConnection
    = TagToContentNodeConnection


type TagToContentNodeConnectionEdge
    = TagToContentNodeConnectionEdge


type TagToPostConnection
    = TagToPostConnection


type TagToPostConnectionEdge
    = TagToPostConnectionEdge


type TagToTaxonomyConnectionEdge
    = TagToTaxonomyConnectionEdge


type Taxonomy
    = Taxonomy


type TaxonomyToContentTypeConnection
    = TaxonomyToContentTypeConnection


type TaxonomyToContentTypeConnectionEdge
    = TaxonomyToContentTypeConnectionEdge


type TermNodeToEnqueuedScriptConnection
    = TermNodeToEnqueuedScriptConnection


type TermNodeToEnqueuedScriptConnectionEdge
    = TermNodeToEnqueuedScriptConnectionEdge


type TermNodeToEnqueuedStylesheetConnection
    = TermNodeToEnqueuedStylesheetConnection


type TermNodeToEnqueuedStylesheetConnectionEdge
    = TermNodeToEnqueuedStylesheetConnectionEdge


type Theme
    = Theme


type UpdateCategoryPayload
    = UpdateCategoryPayload


type UpdateCommentPayload
    = UpdateCommentPayload


type UpdateMediaItemPayload
    = UpdateMediaItemPayload


type UpdatePagePayload
    = UpdatePagePayload


type UpdatePostFormatPayload
    = UpdatePostFormatPayload


type UpdatePostPayload
    = UpdatePostPayload


type UpdateSettingsPayload
    = UpdateSettingsPayload


type UpdateTagPayload
    = UpdateTagPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type UserRole
    = UserRole


type UserToCommentConnection
    = UserToCommentConnection


type UserToCommentConnectionEdge
    = UserToCommentConnectionEdge


type UserToContentRevisionUnionConnection
    = UserToContentRevisionUnionConnection


type UserToContentRevisionUnionConnectionEdge
    = UserToContentRevisionUnionConnectionEdge


type UserToEnqueuedScriptConnection
    = UserToEnqueuedScriptConnection


type UserToEnqueuedScriptConnectionEdge
    = UserToEnqueuedScriptConnectionEdge


type UserToEnqueuedStylesheetConnection
    = UserToEnqueuedStylesheetConnection


type UserToEnqueuedStylesheetConnectionEdge
    = UserToEnqueuedStylesheetConnectionEdge


type UserToMediaItemConnection
    = UserToMediaItemConnection


type UserToMediaItemConnectionEdge
    = UserToMediaItemConnectionEdge


type UserToPageConnection
    = UserToPageConnection


type UserToPageConnectionEdge
    = UserToPageConnectionEdge


type UserToPostConnection
    = UserToPostConnection


type UserToPostConnectionEdge
    = UserToPostConnectionEdge


type UserToUserRoleConnection
    = UserToUserRoleConnection


type UserToUserRoleConnectionEdge
    = UserToUserRoleConnectionEdge


type WPPageInfo
    = WPPageInfo


type WritingSettings
    = WritingSettings
