-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Union exposing (..)


type ContentRevisionUnion
    = ContentRevisionUnion


type MenuItemObjectUnion
    = MenuItemObjectUnion


type PostObjectUnion
    = PostObjectUnion


type TermObjectUnion
    = TermObjectUnion
