-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Enum.MenuNodeIdTypeEnum exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The Type of Identifier used to fetch a single node. Default is "ID". To be used along with the "id" field.

  - DatabaseId - Identify a menu node by the Database ID.
  - Id - Identify a menu node by the (hashed) Global ID.
  - Name - Identify a menu node by it's name

-}
type MenuNodeIdTypeEnum
    = DatabaseId
    | Id
    | Name
list : List MenuNodeIdTypeEnum
list =
    [DatabaseId, Id, Name]
decoder : Decoder MenuNodeIdTypeEnum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "DATABASE_ID" ->
                        Decode.succeed DatabaseId

                    "ID" ->
                        Decode.succeed Id

                    "NAME" ->
                        Decode.succeed Name

                    _ ->
                        Decode.fail ("Invalid MenuNodeIdTypeEnum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
        )
        

{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MenuNodeIdTypeEnum -> String
toString enum____ =
    case enum____ of
        DatabaseId ->
                "DATABASE_ID"


        Id ->
                "ID"


        Name ->
                "NAME"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MenuNodeIdTypeEnum
fromString enumString____ =
    case enumString____ of
        "DATABASE_ID" ->
                Just DatabaseId


        "ID" ->
                Just Id


        "NAME" ->
                Just Name

        _ ->
                Nothing
