-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Taco.Enum.TermNodeIdTypeEnum exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The Type of Identifier used to fetch a single resource. Default is "ID". To be used along with the "id" field.

  - DatabaseId - The Database ID for the node
  - Id - The hashed Global ID
  - Name - The name of the node
  - Slug - Url friendly name of the node
  - Uri - The URI for the node

-}
type TermNodeIdTypeEnum
    = DatabaseId
    | Id
    | Name
    | Slug
    | Uri
list : List TermNodeIdTypeEnum
list =
    [DatabaseId, Id, Name, Slug, Uri]
decoder : Decoder TermNodeIdTypeEnum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "DATABASE_ID" ->
                        Decode.succeed DatabaseId

                    "ID" ->
                        Decode.succeed Id

                    "NAME" ->
                        Decode.succeed Name

                    "SLUG" ->
                        Decode.succeed Slug

                    "URI" ->
                        Decode.succeed Uri

                    _ ->
                        Decode.fail ("Invalid TermNodeIdTypeEnum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
        )
        

{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TermNodeIdTypeEnum -> String
toString enum____ =
    case enum____ of
        DatabaseId ->
                "DATABASE_ID"


        Id ->
                "ID"


        Name ->
                "NAME"


        Slug ->
                "SLUG"


        Uri ->
                "URI"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TermNodeIdTypeEnum
fromString enumString____ =
    case enumString____ of
        "DATABASE_ID" ->
                Just DatabaseId


        "ID" ->
                Just Id


        "NAME" ->
                Just Name


        "SLUG" ->
                Just Slug


        "URI" ->
                Just Uri

        _ ->
                Nothing
